### ISSUE TITLE
Authentication key on fundraising/campaign level

### ISSUE THREAD

**Issue by martintornros** [BetterNowOrg/api-documentation#3]
It would be great to get an authentication key on fundraising/campaign level, to be able to request donations and data related to your own campaign only. In my particular case I need to know whenever a donation has been made to my campaign for UNHCR, but my I do not need to know anything about the UNHCR organization or project, hence I shouldn't need UNHCRs approval to retrieve an authentication key.

Thanks,
Martin

**Comment by prognostikos** [comment]
Hi Martin,

Thanks for your interest in our API, and most of all thanks for your support for UNHCR in Sweden.

Can you tell me a bit more about your envisioned use case? Would you be polling your fundraiser for donations from a script or web service? Would a webhook that pinged an url be more useful? And what would you do with the information that a new donation has been received - update your personal site, or display the list of donations on a site, or something else entirely?

Right now we only provide access to our API to our customers (the charities and event organizers that we work with), but given enough interest I would personally love to make it more widely available.

**Comment by martintornros** [comment]
Hi Matt,

Thanks for your reply.

In short, our installation is a tech-art project for fundraising, that
displays a (digital) candle as a metaphor for the help people give by
donating to UNHCR. In order to keep the candle alive people need to donate
money, e.g. for every € that is donated the candle stays alive for an
additional 10 minutes. This approach adds to the the sense of community
donation, i.e. "we together are keeping the candle burning". The
application is both a web app and a windows console application displayed
in e.g. shopping malls.

Independent of the front-end solution our back-end always needs to know
either (1) whenever a new donation has been given, or (2) how much money
has been donated in total. Basically, the more data we can get on our own
campaign, the better. We really do appreciate the API and/or webhook
solution, since this allows the donors to donate money to UNHCR/Better Now
directly.

Our original idea was to use webhooks or similar, so that indeed sounds
like a great solution. I picture a HTTP POST with all donation data
attached, allowing us to easily update our database on the fly. This should
be a simpler approach than us polling and calling your API explicitly.

If this can be implemented, you would indeed have a great solution and
product for cases like ours and it would open up for many new innovative
and interesting user cases. Please keep us updated.

Best regards,
Martin Törnros

Email: martin@martintornros.com
Phone: 0046-702800054
Web: www.martintornros.com / www.facebook.com/martintornrosdev

2015-09-29 7:08 GMT+02:00 Matt Rohrer <notifications@github.com>:

**Comment by prognostikos** [comment]
Thanks for the info, Martin. Sounds like a really cool project!

What is the timeframe? Is this something you're doing in cooperation with UNHCR or is it an independent art piece?

**Comment by martintornros** [comment]
Thanks Matt,

We are currently developing back- and front-end and aim to be done during
October. By 1 November we hope to have everything ready for testing
(including the payment, hopefully via Better Now) and then have the full
system up and running and published 29 November (first Advent).

The project is currently run and developed independently, and we're setting
up our own nonprofit organization to host it. However, we are open for
discussion with any party that would be interested in a cooperation, not
least with UNHCR or recognized charity organizations.

Regards,
Martin

Email: martin@martintornros.com
Phone: 0046-702800054
Web: www.martintornros.com / www.facebook.com/martintornrosdev

2015-09-29 11:35 GMT+02:00 Matt Rohrer <notifications@github.com>:

**Comment by martintornros** [comment]
Hi Matt,

Are there any updates on my API issue? I am still hoping you will offer API
access on campaign level or implement a webhook solution for developers to
be notified whenever a donation has been made for a certain campaign.

Best regards,
Martin Törnros

Email: martin@martintornros.com
Phone: 0046-702800054
Web: www.martintornros.com / www.facebook.com/martintornrosdev


2015-09-29 13:21 GMT+02:00 Martin Törnros <martintornros@gmail.com>:

**Comment by prognostikos** [comment]
@martintornros I really like the idea of this project so I will do what I can to get you set up by November first. It may be really rough without any UI, but we'll have something in place. I'll first have time to look at it on the 20th - I'll ping you then.

**Comment by martintornros** [comment]
Perfect, thanks! Let me know if you need anything from my side, e.g. if I
should/can do any particular setup in order to do simple testing.

Best,
Martin

2015-10-07 17:13 GMT+02:00 Matt Rohrer <notifications@github.com>:

**Comment by prognostikos** [comment]
Here's the rough idea:

I envision that you'll provide an url (ideally https and with embedded basic auth credentials so you'll know it's us).

I'll POST you the json representation of a donation as defined in the docs when we receive payment for a donation. I'll set it up as a backgroud job with exponential backoff/retries, etc, but will assume that if I get a 2xx response w/in some timeout value like 30seconds that you've received the payload and will not resend.

I can also create an API key for you to be able to only poll your fundraiser for publicly available information, so you can get aggregate info.

More in a few weeks :)

**Comment by prognostikos** [comment]
Closing this as I wrote directly to @martintornros a few weeks ago.
